openapi: 3.0.0
info:
  title: UpTask API
  version: 1.0.0
  description: API para la gestión de proyectos y tareas
servers:
  - url: http://localhost:4000
    description: Servidor local
paths:
  /api/projects:
    $ref: './paths/projects.yaml#/projects'

  /api/projects/{projectId}:
    $ref: './paths/projects.yaml#/singleProject'
  
  /api/projects/{projectId}/tasks:
    $ref: './paths/tasks.yaml#/projectTasks'

  /api/projects/{projectId}/tasks/{taskId}:
    $ref: './paths/tasks.yaml#/singleTask'

components:
  $ref: './components/schemas.yaml'